version: '2'
services:
    shogun-postgis:
        image: mdillon/postgis:9.6-alpine
        ports:
            - 5556:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./postgis/postgresql_init_data:/docker-entrypoint-initdb.d
            - ./postgis/postgresql_data:/var/lib/postgresql/data:Z
