version: '2'
services:
    shogun-postgis:
        image: mdillon/postgis:9.6-alpine
        ports:
            - 5555:5432
        environment:
            POSTGRES_USER: orka
            POSTGRES_PASSWORD: orka
        volumes:
            - ./postgis/postgresql_init_data:/docker-entrypoint-initdb.d
            - ./postgis/postgresql_data:/var/lib/postgresql/data:Z
